export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const BOARD_REPOSITORY = Symbol('BOARD_REPOSITORY');
export const TASK_REPOSITORY = 'TASK_REPOSITORY';
